<?php
var_dump($error);
?>
<form method="POST">
	<table>
		<tr>
			<td>id_sub_category</td>
			<td><input type="text" name="id_sub_category"/></td>
		</tr>
		<tr>
			<td>reference</td>
			<td><input type="text" name="reference"/></td>
		</tr>
		<tr>
			<td>stock</td>
			<td><input type="text" name="stock"/></td>
		</tr>
		<tr>
			<td>prix_uni_ht</td>
			<td><input type="text" name="prix_uni_ht"/></td>
		</tr>
		<tr>
			<td>tva</td>
			<td><input type="text" name="tva"/></td>
		</tr>
		<tr>
			<td>description</td>
			<td><input type="text" name="description"/></td>
		</tr>
		<tr>
			<td>image</td>
			<td><input type="text" name="image"/></td>
		</tr>
		<tr>
			<td>nom</td>
			<td><input type="text" name="nom"/></td>
		</tr>
		<tr>
			<td>poids_uni</td>
			<td><input type="text" name="poids_uni"/></td>
		</tr>
		<tr>
			<td>statut</td>
			<td><input type="text" name="statut"/></td>
		</tr>
		<tr>
			<td>valider</td>
			<td><button type="submit" name="action" value="ajouter"/>Ajouter</button></td>
		</tr>


	</table>


</form>