<form method="POST">
	<div class="admin_produit">
		<div class="row">
			<div class="col">nom</div>
			<div class="col"><input type="text" name="nom" value="<?=htmlentities($produit->getNom())?>"/></div>
		</div>
		<div class="row">
			<div class="col">sous catégorie</div>
			<div class="col">
				<!--<input type="text" name="id_sub_category" value="<?=htmlentities($produit->getSubCategory()->getId())?>"/>-->
				<select name="id_sub_category">
					<?php require('apps/ls_category_admin.php'); ?>
				</select>
			</div>

		</div>
		<div class="row">
			<div class="col">reference</div>
			<div class="col"><input type="text" name="reference" value="<?=htmlentities($produit->getReference())?>"/></div>
		</div>
		<div class="row">
			<div class="col">stock</div>
			<div class="col"><input type="text" name="stock" value="<?=htmlentities($produit->getStock())?>"/></div>
		</div>
		<div class="row">
			<div class="col">prix_uni_ht</div>
			<div class="col"><input type="text" name="prix_uni_ht" value="<?=htmlentities($produit->getPrixUniHt())?>"/></div>
		</div>
		<div class="row">
			<div class="col">tva</div>
			<div class="col"><input type="text" name="tva" value="<?=htmlentities($produit->getTva())?>"/></div>
		</div>
		<div class="row">
			<div class="col">description</div>
			<div class="col"><input type="text" name="description" value="<?=htmlentities($produit->getDescription())?>"/></div>
		</div>
		<div class="row">
			<div class="col">image</div>
			<div class="col"><input type="text" name="image" value="<?=$http?><?=htmlentities($produit->getImage())?>"/></div>
		</div>
		<div class="row">
			<div class="col">poids_uni</div>
			<div class="col"><input type="text" name="poids_uni" value="<?=htmlentities($produit->getPoidsUni())?>"/></div>
		</div>
		<div class="row">
			<div class="col">statut</div>
			<div class="col"><input type="text" name="statut" value="<?=htmlentities($produit->getStatut())?>"/></div>
		</div>
		<div class="row">
			<div class="col">valider</div>
			<div class="col"><button type="submit" name="action" value="<?=$action?>"/>Ajouter</button></div>
		</div>


	</div>


</form>