<div class="category-content">
	<div class="category"></div>

	<div class="category">
		<a href="index.php?page="><img src="images/man_dream.jpg" alt="man_dream" class="img-category"/><h2>HOMME</h2></a>
		<nav>
			<ul>
				<li><a href="index.php?page=sportifs_celebres">Sportifs célèbres</a></li>
				<li><a href="index.php?page=super_heros">Super héros</a></li>
				<li><a href="index.php?page=super_seducteur">Super séducteur</a></li>
				<li><a href="index.php?page=cauchemars_homme">Cauchemars</a></li>
			</ul>	
		</nav>
	</div>

	<div class="category">
		<a href="index.php?page="><img src="images/woman_dream.jpg" alt="woman_dream" class="img-category"/><h2>FEMME</h2></a>
		<nav>
			<ul>
				<li><a href="index.php?page=prince_charmant">Prince charmant</a></li>
				<li><a href="index.php?page=pretty_woman">Pretty woman</a></li>
				<li><a href="index.php?page=celebrites">Célébrités</a></li>
				<li><a href="index.php?page=cauchemars_femme">Cauchemars</a></li>
			</ul>	
		</nav>
	</div>

	<div class="category">
		<a href="index.php?page="><img src="images/children_dream2.jpg" alt="children_dream" class="img-category"/><h2>ENFANTS</h2></a>
		<nav>
			<ul>
				<li><a href="index.php?page=superheros">Superhéros</a></li>
				<li><a href="index.php?page=bonbons">Bonbons</a></li>
				<li><a href="index.php?page=voyage_dans_l_espace">Voyage dans l'espace</a></li>
				<li><a href="index.php?page=princes_et_princesses">Princes et princesses</a></li>
			</ul>	
		</nav>
	</div>

	<div class="category">
		<a href="index.php?page="><img src="images/allpublic_dream.jpg" alt="allpublic_dream" class="img-category"/><h2>TOUS PUBLICS</h2></a>
		<nav>
			<ul>
				<li><a href="index.php?page=reussite">Réussite sociale</a></li>
				<li><a href="index.php?page=reussite_sentimentale">Réussite sentimentale</a></li>
				<li><a href="index.php?page=reussite_financiere">Réussite financière</a></li>
				<li><a href="index.php?page=cauchemars">Cauchemars</a></li>
			</ul>	
		</nav>
	</div>
</div>

<?php

require('apps/ls_sub_category.php')

?>