<div class="category-content">
	<div class="category">
		<img src="<?=$category->getImage()?>" alt="<?=$category->getNom()?>" class="img-category"/><h2><?=htmlentities($category->getNom())?></h2>
	</div>
	<div class="<?=$admin?> lsBtnAdmin">
		<div class="btn"><a href="index.php?page=admin_category&id_category=<?=$category->getId()?>&action=edit">Modifier la catégorie</a></div>
		<div class="btn"><a href="index.php?page=admin_category&id=<?=$categorie->getId()?>&action=create">Création Sous-Catégorie</a></div>
	</div>
	<div class="subCategory">
		<nav>
			<ul>
				<?php require('apps/ls_sub_category.php');?>
			</ul>
		</nav>
	</div>
</div>				
				<!--
				<li><a href="index.php?page=super_heros">Super héros</a></li>
				<li><a href="index.php?page=super_seducteur">Super séducteur</a></li>
				<li><a href="index.php?page=cauchemars_homme">Cauchemars</a></li>
			</ul>	
		</nav>
	</div>

	<div class="category">
		<a href="index.php?page=femme"><img src="images/woman_dream.jpg" alt="woman_dream" class="img-category"/><h2>FEMME</h2></a>
		<nav>
			<ul>
				<li><a href="index.php?page=prince_charmant">Prince charmant</a></li>
				<li><a href="index.php?page=pretty_woman">Pretty woman</a></li>
				<li><a href="index.php?page=celebrites">Célébrités</a></li>
				<li><a href="index.php?page=cauchemars_femme">Cauchemars</a></li>
			</ul>	
		</nav>
	</div>

	<div class="category">
		<a href="index.php?page=enfants"><img src="images/children_dream2.jpg" alt="children_dream" class="img-category"/><h2>ENFANTS</h2></a>
		<nav>
			<ul>
				<li><a href="index.php?page=superheros">Superhéros</a></li>
				<li><a href="index.php?page=bonbons">Bonbons</a></li>
				<li><a href="index.php?page=voyage_dans_l_espace">Voyage dans l'espace</a></li>
				<li><a href="index.php?page=princes_et_princesses">Princes et princesses</a></li>
			</ul>	
		</nav>
	</div>

	<div class="category">
		<a href="index.php?page=tous_publics"><img src="images/allpublic_dream.jpg" alt="allpublic_dream" class="img-category"/><h2>TOUS PUBLICS</h2></a>
		<nav>
			<ul>
				<li><a href="index.php?page=reussite_sociale">Réussite sociale</a></li>
				<li><a href="index.php?page=reussite_sentimentale">Réussite sentimentale</a></li>
				<li><a href="index.php?page=reussite_financiere">Réussite financière</a></li>
				<li><a href="index.php?page=cauchemars_publics">Cauchemars</a></li>
			</ul>	
		</nav>
	</div>
</div>

<?php
require('apps/ls_sub_category.php')
?>
-->