<div class="owl-carousel">
	<?php require ('apps/ls_produits_notes.php');?>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
		<script src="public/scripts/owl.carousel.min.js"></script>
		<script>$(document).ready(function(){
		var options=
		{
			"items":1,
			"dots":true,
			"autoplay":true,
			"loop":true,
		}
  	$(".owl-carousel").owlCarousel(options);});</script>