
<form method="POST">	

	<div class="container">
		<div class="row">
			<div style="color:white" class="col">Login</div>
			<div style="color:white" class="col"><input type="text" name="login"/></div>
		</div>
		<div class="row">
			<div class="col">Password</div>
			<div class="col"><input type="password" name="password"/></div>
		</div>

		<br>

		<div class="row">
			<div class="col"><button class ="btn" type="submit" name="action" value="ajouter"/>Connexion</button></div>
		</div>
	</div>

</form>