
<form method="POST">

	<table>
		<tr>
			<td>Login</td>
			<td><input type="text" name="login"/></td>
		</tr>
		<tr>

			<td>Password</td>
			<td><input type="password" name="password"/></td>
		</tr>
		<tr>
			<td>Valider</td>
			<td><button type="submit" name="action" value="ajouter"/>Ajouter</button></td>

			<td>password</td>
			<td><input type="password" name="password"/></td>
		</tr>
		<tr>
			
			<td>valider</td>
			<td><button type="submit" name="action" value="ajouter"/>Connexion</button></td>

		</tr>
	</table>

	<div class="container">
		<div class="row">
			<div class="col">Login</div>
			<div class="col"><input type="text" name="login"/></div>
		</div>
		<div class="row">
			<div class="col">Password</div>
			<div class="col"><input type="password" name="password"/></div>
		</div>
		<div class="row">
			<div class="col"><button class ="btn" type="submit" name="action" value="ajouter"/>Connexion</button></div>
		</div>
	</div>

</form>