<div class="detailsPanier">
	<h4>Nom du client:<?=$panier->getUser()->getLogin()?></h4>
	<h4>Montant du panier:<?=$panier->getPrix()?></h4>
	<h4>Liste des produits concernés:</h4>
	<div class="container"><?php require('apps/admin_panier_item.php'); ?></div>
		<form method="post" action="">
			<button name="id_panier" value="<?=$panier->getId()?>" type="submit">Valider ce panier</button>
		</form>
</div>