<table>
    <tr>
		<td class="td_panier td_panier_titre" >PRIX UNIT</td>
		<td class="td_panier td_panier_titre" >NOMBRE</td>
		<td class="td_panier td_panier_titre" >POIDS</td>
		<td class="td_panier td_panier_titre" >DATE</td>
	</tr>
	<tr>
		<td class="td_panier td_panier_content"><?php echo number_format($panier->getPrix(),2);?></td>
		<td class="td_panier td_panier_content"><?php echo $panier->getNombreProduits();?></td>
		<td class="td_panier td_panier_content"><?php echo $panier->getPoids();?></td>
		<td class="td_panier td_panier_content"><?php echo date('d/m/Y H:i', strtotime($panier->getDate()));?></td>
		
	</tr>

	<tr>
		<td style="background-color:grey;color:white" class="td_panier td_produit_titre" colspan="4">PRODUITS DU PANIER</td>
	</tr>
	<tr>
	    <td style="background-color:grey;color:white"class="td_panier td_produit_titre">NOM</td>
		<td style="background-color:grey;color:white"class="td_panier td_produit_titre">PRIX TTC</td>
		<td style="background-color:grey;color:white"class="td_panier td_produit_titre">TVA</td>
		<td style="background-color:grey;color:white"class="td_panier td_produit_titre">REFERENCE</td>
	</tr>
	<?php require('apps/panier_item.php'); ?>
</table>

	
