<li>
<div class="affiche_sub">
	<h2 class="affiche_sub_nom"><?php echo $produit->getNom();?></h2>

	<h2 class="affiche_sub_nom"><?php echo $produit->getDescription();?></h2>



	<!--<form method="POST">
         <input type="hidden" name="id" value="<?php echo $produit->getId(); ?>"/>
         <input type="submit" value="voir le produit"/>
	</form>-->
	<div class="btn"><a style="color:white;text-decoration:none"href="index.php?page=produit&id_produit=<?=$produit->getId()?>">Voir le produit</a></div>
	
</div>

</li>