<table 	class="tbl_panier"> 
    <tr>
    	<td style="background-color:orange" colspan="4">PANIER</td>
    <tr>
   

    <tr>
		<td style="background-color:orange"class="td_panier" >PRIX UNIT</td>
		<td style="background-color:orange"class="td_panier" >NOMBRE</td>
		<td style="background-color:orange"class="td_panier" >POIDS</td>
		<td style="background-color:orange"class="td_panier" >DATE</td>
	</tr>
</table>


