<li>
<div class="affiche_sub">
	<h2 class="affiche_sub_nom"><?php echo $produit->getNom();?></h2>

	<h2 class="affiche_sub_nom"><?php echo $produit->getDescription();?></h2>



	<form method="POST">
         <input type="hidden" name="id" value="<?php echo $produit->getId(); ?>"/>
         <a href="index.php?page=produit&id=<?=$produit->getId()?>">Voir le produit</a>
	</form>
	
	
</div>

</div>
</li>