<h1 class="white">Votre panier</h1>
<div class="container panier">

	<?php require('apps/ls_produits_panier.php'); ?>
	<div class="<?=$panier_vide?>">
		Votre panier est vide.
	</div>
</div>
<div class="container info_panier <?=$no_panier?>">
	<div class="poids">
		Poids total : <?=floatval($panier->getPoids())?> g
	</div>
	<div class="prix">
		Montant total : <?=floatval($panier->getPrix())?> €
	</div>
	<form action="" method="POST">
		<button class="btn" type="submit" name="action" value="validate">Finaliser votre commande</button>
	</form>
</div>