<h1><?=htmlentities($produit->getNom())?></h1>
<h3><?=htmlentities($produit->getReference())?></h3>
<div class="right note">Note moyenne : <?=htmlentities($produit->setMoyenne())?>/5</div>
<picture><img src="<?=$produit->getImage()?>" alt="image <?=htmlentities($produit->getNom())?>"></picture>
<p><?=htmlentities($produit->getDescription())?></p>
<p>Stock restant : <?=htmlentities($produit->getStock())?></p>
<div class="ht">Prix HT : <?=htmlentities($produit->getPrixUniHt())?> €</div>
<div class="ttc">Prix TTC : <?=htmlentities($produit->getPrixUniTtc())?> €</div>
<form action="" method="POST">
	<button class="btn" type="submit" name="id_produit" value="<?=$produit->getId()?>">Ajouter au panier</button>
</form>
<div class="<?=$admin?>">
	<button class="btn"><a href="index.php?page=admin_produit&id_produit=<?=$produit->getId()?>">Modifier</a></button>
	<button class="btn"><a href="index.php?page=produit&id_produit=<?=$produit->getId()?>&action=supprimer">Supprimer</a></button>
</div>
<h2>Avis</h2>
<div class="container <?=$no_avis?>">
	Aucun avis pour ce produit
</div>
<div class="ajout <?=$ajout_ok?>">
	<div class="btn"><a href="index.php?page=avis&id_produit=<?=$produit->getId()?>&action=creer">Ajouter un avis</a></div>
</div>
<div class="modif <?=$modif_ok?>">
	<button class="btn"><a href="index.php?page=avis&id_produit=<?=$produit->getId()?>&action=modifier">Modifier votre avis</a></button>
</div>
<div class="container <?=$avis_class?>"><?php require('apps/ls_avis.php'); ?></div>