<div class="error"><?=$error?></div>
<form method="POST">
	<table>
		<tr>
			<td>nom</td>
			<td><input type="text" name="nom"/></td>
		</tr>
		<tr>
			<td>prenom</td>
			<td><input type="text" name="prenom"/></td>
		</tr>
		<tr>
			<td>email</td>
			<td><input type="email" name="email"/></td>
		</tr>
		<tr>
			<td>login</td>
			<td><input type="text" name="login"/></td>
		</tr>
		<tr>
			<td>password</td>
			<td><input type="password" name="password"/></td>
		</tr>
		<tr>
			<td>confirm password</td>
			<td><input type="password" name="passwordBis"/></td>
		</tr>
		
		<tr>
			<td>sexe</td>
			<td>
				<select name="sexe">
					<option value="1">Homme</option>
					<option value="2">Femme</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>date de naissance</td>
			<td><input type="text" name="date_naissance"/></td>
		</tr>
		<tr>
			<td>telephone</td>
			<td><input type="text" name="telephone"/></td>
		</tr>
		<tr>
			<td></td>
			<td><button type="submit" name="action" value="ajouter"/>Ajouter</button></td>
		</tr>


	</table>


</form>