
	<table class="register">
		<form method="POST">
		<tr>
			<td class="white">Nom</td>
			<td><input type="text" name="nom"/></td>
		</tr>
		<tr>
			<td class="white">Prénom</div>
			<td><input type="text" name="prenom"/></td>
		</tr>
		<tr>
			<td class="white">E-mail</td>
			<td><input type="email" name="email"/></td>
		</tr>
		<tr>
			<td class="white">Login</td>
			<td><input type="text" name="login"/></td>
		</tr>
		<tr>
			<td class="white">Password</td>
			<td><input type="password" name="password"/></td>
		</tr>
		<tr>
			<td class="white">Confirm password</td>
			<td><input type="password" name="passwordBis"/></td>
		</tr>
		
		<tr>
			<td class="white">Sexe</td>
			<td>
				<select name="sexe">
					<option value="1">Homme</option>
					<option value="2">Femme</option>
				</select>
			</td>
		</tr>
		<tr>
			<td class="white">Date de naissance</td>
			<td><input type="text" name="date_naissance"/></td>
		</tr>
		<tr>
			<td class="white">Téléphone</td>
			<td><input type="text" name="telephone"/></td>
		</tr>

		

		<tr>
			<td colpsan="2" class="white"><h4>Adresse de facturation</h4></td>
		</tr>

	

		<tr>
			<td class="white">Nom de l'adresse</td>
			<td><input type="text" name="nom_adresse1"></td>
		</tr>
		<tr>
			<td class="white">Numéro</td>
			<td><input type="text" name="numero1"></td>
		</tr>
		<tr>
			<td class="white">Rue</td>
			<td><input type="text" name="rue1"></td>
		</tr>
		<tr>
			<td class="white">Code postal</td>
			<td><input type="text" name="code_postal1"></td>
		</tr>
		<tr>
			<td class="white">Ville</td>
			<td><input type="text" name="ville1"></td>
		</tr>

		

		<tr>
			<td colpsan="2" class="white"><h4>Adresse de livraison</h4></td>
		</tr>



		<tr>
			<td class="white">Nom de l'adresse</td>
			<td><input type="text" name="nom_adresse2"></td>
		</tr>
		<tr>
			<td class="white">Numéro</td>
			<td><input type="text" name="numero2"></td>
		</tr>
		<tr>
			<td class="white">Rue</td>
			<td><input type="text" name="rue2"></td>
		</tr>
		<tr>
			<td class="white">Code postal</td>
			<td><input type="text" name="code_postal2"></td>
		</tr>
		<tr>
			<td class="white">Ville</td>
			<td><input type="text" name="ville2"></td>
		</tr>
		<tr>
			<td></td>
			<td><button type="submit" name="action" value="ajouter"/>Ajouter</button></td>
		</tr>


	


</form>

</table>