<div class="sidebar">
	<nav class="side">
		<ul class="menuSide">
			<li><a href="index.php?page=home">Rechercher</a></li><!--A VOIR: vers où pointe ce lien?-->
			<li><a href="index.php?page=admin_avis">Gestion Avis</a></li>
			<li><a href="index.php?page=admin_produits">Gestion Produits</a></li>
			<li><a href="index.php?page=ls_admin_paniers">Gestion Paniers</a></li>
			<li><a href="index.php?page=logout">Se déconnecter</a></li>
		</ul>
	</nav>
</div>