<nav class="side">
	<ul class="menuSide">
		<li><a href="index.php?page=home">Rechercher</a>
		<form method="GET">
		    <input type="hidden" name="page" value="shearch_result"/>
            <input id="ajax" type="text" name="recherche"/>
		    <input type="submit" value="rechercher"/>
		    </form></li><!--A VOIR: vers quelle page pointe ce lien?-->
		    <script>


                 $(document).ready(function(){

                 	$('#ajax').keyup(function(){
                      $.ajax({url: "traitement_produits.php", success: function(result){
                      $("#ajax").html(result);

                       }});
                 	
                 	})
                 });
		    </script></li><!--A VOIR: vers où pointe ce lien?-->
		<li><a href="index.php?page=panier">Panier</a></li>
		<li><a href="index.php?page=profil_user">Mon compte</a></li>
		<li><a href="index.php?page=admin_avis">Gestion Avis</a></li>
		<li><a href="index.php?page=admin_produits&action=create">Création Produits</a></li>
		<li><a href="index.php?page=admin_category&action=create">Gestion Catégories</a></li>
		<li><a href="index.php?page=admin">Administration</a></li>
		<li><a href="index.php?page=logout">Se déconnecter</a></li>
	</ul>
</nav>