<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<link rel="stylesheet" type="text/css" href="public/styles/reset.css" />
	<link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="public/fonts/font-awesome.min.css">
	<link rel="stylesheet" href="public/styles/owl.carousel.css">
	<link rel="stylesheet" type="text/css" href="public/styles/style.css"/>
	<link rel="stylesheet" type="text/css" href="public/styles/bootstrap.min.css"/>
	<link href='https://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet' type='text/css'>
	<title>Accueil</title>
</head>
<body>
	<main class="main">
		<div class="hautPage">
			<?php require('apps/menu.php');?>
		</div>
		<div class="clearfix">
			<div class="sidebar">
				<?php require('apps/sidebar.php');?>
			</div>
			<div class="content">
				<?php require('apps/content.php');?>
			</div>
		</div>
		<?php require('apps/footer.php');?>
  	</main>  	
</body>
</html>