<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<link rel="stylesheet" type="text/css" href="styles/reset.css" />
	<link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="fonts/css/font-awesome.css">
	<link rel="stylesheet" href="styles/owl.carousel.css">
	<link rel="stylesheet" type="text/css" href="styles/style.css"/>
	<title>Accueil</title>
</head>
<body>
	<main class="main">
		<div class="hautPage">
		<?php require('apps/menu.php');?>
		<div class="content">
		<?php require('apps/sidebar.php');?>
		</div>
		</div>
		<?php require('apps/footer.php');?>
  	</main>  	
</body>
</html>