




	<div class="sub_cat">


			<h3 style="color:#2E2E2E" id="h2_sub"><?=$subcategory->getNom()?></h3>
			<p  style="color:#2E2E2E"><?=$subcategory->getDescription()?></p>
			


			<div class="btn"><a style="color:#2E2E2E" href="index.php?page=admin_category&action=edit&id=<?=$subcategory->getCategories()->getId()?>&id_sub_category=<?=$subcategory->getId()?>">Modifier la sous catégorie</a>

				<div class="affiche_sub">
					<h2 style="color:#2E2E2E" class="affiche_sub_nom"><?php echo $produit->getNom();?></h2>

					<h2 style="color:#2E2E2E" class="affiche_sub_nom"><?php echo $produit->getDescription();?></h2>
                </div>


				
					<div class="btn"><a style="color:#2E2E2E;text-decoration:none"href="index.php?page=produit&id_produit=<?=$produit->getId()?>">Voir le produit</a></div>
			
		</div>

			<div class="btn <?=$admin?>">
				<a href="index.php?page=admin_category&action=edit&id=<?=$subcategory->getCategories()->getId()?>&id_sub_category=<?=$subcategory->getId()?>">Modifier la sous catégorie</a>
			</div>

			<?php require('apps/ls_produits.php');?>


    </div>


<div class="sub_cat">
	<h2 id="h2_sub"><?=htmlentities($subcategory->getNom())?></h2>
	<p><?=htmlentities($subcategory->getDescription())?></p>
	<br>
	<div class="<?=$admin?>">
		<div class="btn"><a href="index.php?page=admin_category&action=edit&id=<?=$subcategory->getCategories()->getId()?>&id_sub_category=<?=$subcategory->getId()?>">Modifier la sous catégorie</a></div>
	</div>
	<?php require('apps/ls_produits.php'); ?>
</div>

